version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    user: root
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
    depends_on:
      - docker
      
  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    restart: always 
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      - net            
networks:
  net:

volumes:
  jenkins-data:
  jenkins-docker-certs: